# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans4@overlook.net",
  "avatarPath": "torrance.png",
  "name": "Torrance",
  "password": "shining1",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/users/69cfd56756fdcaa5f1398238/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="default-avatar.png"
Content-Type: image/png

< C:/computer_science_and_engineering/node_js/2503027-six-cities-6/upload/default-avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0NzBiYzM4M2UzMGRiNjc5ZGZhYzJkMiIsImlhdCI6MTY4NTk3NTQ4MiwiZXhwIjoxNjg2MTQ4MjgyfQ.Gq2-B1egouAnMxmXlR2ElVT6wCa97PS6lxzVI8LnGvo

###
